# fly.toml file generated for destiny-definitions-archive on 2022-11-22T21:34:44Z

app = "destiny-definitions-archive"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  NODE_ENV = "production"
  STORAGE_VOLUME = "/data"
  S3_BUCKET = "destiny-definitions"
  S3_REGION = "eu-west-1"
  SWAP = true

[build.args]
  SWAP=true

[mounts]
  source="destiny_definitions_archive_volume"
  destination="/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 100
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = true
    [services.http_checks.headers]